Repository ricora/alg.tus-ricora.com, pull requests merged in 2023-12, with the labels that each got.

#17 chore: lint-stagedのPrettierの対象にMDXとCSSを追加
  lint-staged.config.js
  src/styles/global.css
Labels: bug, chore

#12 chore: FormatとLintとBuildテストをするCIを整備
  .github/workflows/ci.yml
  package.json
Labels: chore

#11 chore: Renovateを導入
  renovate.json
Labels: chore

#21 feat: MDXから記事のページを生成する
  .vscode/settings.json
  astro.config.ts
  bun.lockb
  package.json
  postcss.config.js
  src/components/Elements/Callout/Callout.astro
  src/components/Elements/Callout/CalloutTitle.astro
  src/components/Elements/Callout/callouts.ts
  src/components/Elements/Callout/index.ts
  src/components/Elements/CodeBlock/CodeBlock.astro
  src/components/Elements/CodeBlock/index.ts
  src/components/Elements/CodeBlock/shiki.css
  src/components/Elements/Embed/OEmbed.astro
  src/components/Elements/Embed/index.ts
  src/components/Elements/Embed/oEmbed.css
  src/components/Elements/LinkCard/Link.astro
  src/components/Elements/LinkCard/LinkCard.astro
  src/components/Elements/LinkCard/index.ts
  src/components/Elements/Tooltip.tsx
  src/content/config.ts
  src/content/posts/hello-world-v2/imgs/ricora.svg
  src/content/posts/hello-world-v2/index.mdx
  src/env.d.ts
  src/lib/remark-plugins/remarkCallout.test.ts
  src/lib/remark-plugins/remarkCallout.ts
  src/lib/remark-plugins/remarkEmbed.test.ts
  src/lib/remark-plugins/remarkEmbed.ts
  src/lib/remark-plugins/remarkLinkCard.test.ts
  src/lib/remark-plugins/remarkLinkCard.ts
  src/lib/runtime.ts
  src/lib/theme.ts
  src/pages/posts/[...slug]/index.astro
  tailwind.config.ts
  vite.config.ts
Labels: enhancement
